name: Publish NuGet package to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Baclib.Bacnet.Types/Baclib.Bacnet.Types.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore src/Baclib.Bacnet.Types/Baclib.Bacnet.Types.csproj

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./nupkg src/Baclib.Bacnet.Types/Baclib.Bacnet.Types.csproj

      #- name: Publish to GitHub Packages
      #  run: dotnet nuget push ./nupkg/*.nupkg --source "https://nuget.pkg.github.com/baclib" --api-key ${{ secrets.GITHUB_TOKEN }}
      #  env:
      #    NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up packages
        run: rm -rf ./nupkg

      - name: Done
        run: echo "NuGet package published to GitHub Packages!"